name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Strapi is not yet compatible with node 16
        node: ["14", "16"]
    name: integration-tests (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Launch tests
        run: yarn test

  playground_build_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["14"]
    name: playground-build (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./playground/node_modules
          key: ${{ hashFiles('playground/yarn.lock') }}
      - name: Install dependencies
        run: yarn --dev && yarn --cwd ./playground
      - name: Build Strapi playground
        run: yarn playground:build

  linter_check:
    runs-on: ubuntu-latest
    name: style-check
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        run: yarn --dev
      - name: Run style check
        run: yarn style
      - name: Yaml Style
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
